apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: jenkins
  labels:
    app: jenkins
spec:
  selector:
    matchLabels:
      app: jenkins
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      nodeSelector:
        node: master
      containers:
      - image: jenkins/jenkins:lts
        name: jenkins
        ports:
        - containerPort: 8080
          name: jenkins
       #volumeMounts:
        #- name: jenkins-persistent-storage
         # mountPath: LN
      #volumes:
     # - name: jenkins-persistent-storage
       # persistentVolumeClaim:
        #  claimName: jenkins-pvc-new

